# Generated by Django 4.2.2 on 2023-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='text',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
